### ISSUE TITLE
Pratia 7_Costos y Juicio Experto

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-entrevista_gestion-de-proyecto#1]
[PRACTICA7.pdf](https://github.com/user-attachments/files/17547696/PRACTICA7.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by luzm23** [comment]
https://github.com/SistemasTecTlaxiaco/MejorandoelCampo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
